project_id = "ecfxulsjdqcqavbaglwm"

[functions.marketing-agent]
verify_jwt = false

[functions.analytics-agent]
verify_jwt = false

[functions.sales-agent]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.payment-proof]
verify_jwt = false

[functions.create-card-payment]
verify_jwt = false

[functions.capture-card-payment]
verify_jwt = false
