import { useEffect, useState } from "react";
import { FileClock, RefreshCw } from "lucide-react";
import { AdminLayout } from "@/components/admin/AdminLayout";
import { PageHeader } from "@/components/admin/PageHeader";
import { EmptyState, LoadingState } from "@/components/ui/data-state";
import { useCompany } from "@/hooks/useCompany";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

type AuditEntry = { id: string; actor_type: string; actor_name: string; action: string; target_type: string | null; target_id: string | null; created_at: string };
export default function Audit() { const { company } = useCompany(); const [entries, setEntries] = useState<AuditEntry[]>([]); const [loading, setLoading] = useState(true); const load = async () => { if (!company) return; setLoading(true); const { data, error } = await supabase.from("audit_logs").select("id,actor_type,actor_name,action,target_type,target_id,created_at").eq("company_id", company.id).order("created_at", { ascending: false }).limit(100); if (error) toast.error("Não foi possível carregar o audit log."); setEntries((data as AuditEntry[]) ?? []); setLoading(false); }; useEffect(() => { load(); }, [company?.id]); return <AdminLayout title="Audit log"><div className="space-y-8"><PageHeader eyebrow="Sistema / Segurança" title="Audit log" description="Registo das ações realizadas na operação por pessoas e agentes." actions={<button type="button" onClick={load} className="inline-flex h-9 items-center gap-2 border border-[#ded9d0] bg-[#fffdf9] px-3 text-sm font-semibold text-[#5f625d]"><RefreshCw className="h-3.5 w-3.5" />Atualizar</button>} />{loading ? <LoadingState label="A carregar registos" /> : entries.length === 0 ? <EmptyState title="Ainda não existem registos" description="As ações importantes da operação aparecerão aqui quando forem registadas pelo backend." /> : <section className="border border-[#ded9d0] bg-[#fffdf9]">{entries.map((entry) => <div key={entry.id} className="grid gap-3 border-b border-[#ebe7df] px-5 py-4 last:border-0 sm:grid-cols-[1fr_180px_160px]"><div className="flex items-start gap-3"><div className="mt-0.5 grid h-7 w-7 place-items-center bg-[#f1eee7] text-[#2c6457]"><FileClock className="h-3.5 w-3.5" /></div><div><div className="text-sm font-semibold text-[#202522]">{entry.action}</div><div className="mt-1 text-xs text-[#747b73]">{entry.target_type || "Operação"}{entry.target_id ? ` · ${entry.target_id}` : ""}</div></div></div><div className="text-xs text-[#5f625d]">{entry.actor_name}<div className="mt-1 text-[10px] uppercase text-[#979c95]">{entry.actor_type}</div></div><time className="text-xs text-[#747b73] sm:text-right">{new Intl.DateTimeFormat("pt-PT", { dateStyle: "medium", timeStyle: "short" }).format(new Date(entry.created_at))}</time></div>)}</section>}</div></AdminLayout>; }
