import { useEffect, useState } from "react";
import { RefreshCw, Users } from "lucide-react";
import { AdminLayout } from "@/components/admin/AdminLayout";
import { PageHeader } from "@/components/admin/PageHeader";
import { EmptyState, LoadingState } from "@/components/ui/data-state";
import { useCompany } from "@/hooks/useCompany";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

type Member = { id: string; user_id: string; role: string; created_at: string };
export default function Team() { const { company } = useCompany(); const [members, setMembers] = useState<Member[]>([]); const [loading, setLoading] = useState(true); const load = async () => { if (!company) return; setLoading(true); const { data, error } = await supabase.from("company_members").select("id,user_id,role,created_at").eq("company_id", company.id).order("created_at"); if (error) toast.error("Não foi possível carregar a equipa."); setMembers((data as Member[]) ?? []); setLoading(false); }; useEffect(() => { load(); }, [company?.id]); return <AdminLayout title="Equipa"><div className="space-y-8"><PageHeader eyebrow="Definições / Equipa" title="Equipa e funções" description="Veja quem tem acesso a esta operação e o papel atribuído a cada pessoa." actions={<button type="button" onClick={load} className="inline-flex h-9 items-center gap-2 border border-[#ded9d0] bg-[#fffdf9] px-3 text-sm font-semibold text-[#5f625d]"><RefreshCw className="h-3.5 w-3.5" />Atualizar</button>} />{loading ? <LoadingState label="A carregar equipa" /> : members.length === 0 ? <EmptyState title="Nenhum membro encontrado" description="A equipa será criada quando existir uma associação à empresa." /> : <section className="border border-[#ded9d0] bg-[#fffdf9]"><div className="grid grid-cols-[1fr_120px_150px] border-b border-[#ded9d0] bg-[#f1eee7] px-5 py-3 font-mono text-[10px] uppercase tracking-[0.12em] text-[#979c95]"><span>Membro</span><span>Função</span><span>Entrada</span></div>{members.map((member) => <div key={member.id} className="grid grid-cols-[1fr_120px_150px] items-center border-b border-[#ebe7df] px-5 py-4 last:border-0"><div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center bg-[#e9eee9] text-[#2c6457]"><Users className="h-4 w-4" /></div><div><div className="text-sm font-semibold">{member.user_id.slice(0, 8)}…</div><div className="text-xs text-[#979c95]">ID de utilizador</div></div></div><span className="text-sm capitalize text-[#5f625d]">{member.role}</span><span className="text-xs text-[#747b73]">{new Intl.DateTimeFormat("pt-PT", { dateStyle: "medium" }).format(new Date(member.created_at))}</span></div>)}</section>}</div></AdminLayout>; }
